/* It had generated by DirectStruct v1.4.5 */
#include "IDL_dag_batches_tasks.dsc.h"

#ifndef FUNCNAME_DSCLOG_dag_batches_tasks
#define FUNCNAME_DSCLOG_dag_batches_tasks	DSCLOG_dag_batches_tasks
#endif

#ifndef PREFIX_DSCLOG_dag_batches_tasks
#define PREFIX_DSCLOG_dag_batches_tasks	printf( 
#endif

#ifndef NEWLINE_DSCLOG_dag_batches_tasks
#define NEWLINE_DSCLOG_dag_batches_tasks	"\n"
#endif

int FUNCNAME_DSCLOG_dag_batches_tasks( dag_batches_tasks *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.schedule_name[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->schedule_name );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.batch_name[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->batch_name );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.order_index[%d]" NEWLINE_DSCLOG_dag_batches_tasks , pst->order_index );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.program_and_params[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->program_and_params );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.timeout[%d]" NEWLINE_DSCLOG_dag_batches_tasks , pst->timeout );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.begin_datetime[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->begin_datetime );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.end_datetime[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->end_datetime );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.progress[%d]" NEWLINE_DSCLOG_dag_batches_tasks , pst->progress );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.error[%d]" NEWLINE_DSCLOG_dag_batches_tasks , pst->error );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.status[%d]" NEWLINE_DSCLOG_dag_batches_tasks , pst->status );
	return 0;
}
