-- It had generated by DirectStruct v1.4.5

CREATE TABLE dag_batches_info
(
	schedule_name	CHARACTER VARYING(64) NOT NULL ,
	batch_name	CHARACTER VARYING(64) NOT NULL ,
	batch_desc	CHARACTER VARYING(64) ,
	view_pos_x	INTEGER ,
	view_pos_y	INTEGER ,
	interrupt_by_app	INTEGER ,
	begin_datetime	CHARACTER VARYING(19) ,
	end_datetime	CHARACTER VARYING(19) ,
	progress	INTEGER
) ;

CREATE UNIQUE INDEX dag_batches_info_idx1 ON dag_batches_info ( schedule_name , batch_name ) ;
