/* It had generated by DirectStruct v1.4.5 */
#ifndef _H_dag_batches_info_ESQL_
#define _H_dag_batches_info_ESQL_

#define _PQSQL

#include <ecpglib.h>
#include <ecpgerrno.h>
#include <sqlca.h>

#include "IDL_dag_batches_info.dsc.h"

#undef SQLCODE
#define SQLCODE		(int)(sqlca.sqlcode)

#undef SQLSTATE
#define SQLSTATE	sqlca.sqlstate

#undef SQLDESC
#define SQLDESC		sqlca.sqlerrm.sqlerrmc

#ifndef SQLNOTFOUND
#define SQLNOTFOUND	100
#endif


EXEC SQL BEGIN DECLARE SECTION ;
	extern char dag_batches_info_schedule_name[ 64 + 1 ] ;	extern short dag_batches_info_schedule_name_id ;
	extern char dag_batches_info_batch_name[ 64 + 1 ] ;	extern short dag_batches_info_batch_name_id ;
	extern char dag_batches_info_batch_desc[ 64 + 1 ] ;	extern short dag_batches_info_batch_desc_id ;
	extern int dag_batches_info_view_pos_x ;	extern short dag_batches_info_view_pos_x_id ;
	extern int dag_batches_info_view_pos_y ;	extern short dag_batches_info_view_pos_y_id ;
	extern int dag_batches_info_interrupt_by_app ;	extern short dag_batches_info_interrupt_by_app_id ;
	extern char dag_batches_info_begin_datetime[ 19 + 1 ] ;	extern short dag_batches_info_begin_datetime_id ;
	extern char dag_batches_info_end_datetime[ 19 + 1 ] ;	extern short dag_batches_info_end_datetime_id ;
	extern int dag_batches_info_progress ;	extern short dag_batches_info_progress_id ;
EXEC SQL END DECLARE SECTION ;

#define	TFLIST_dag_batches_info \
	schedule_name , \
	batch_name , \
	batch_desc , \
	view_pos_x , \
	view_pos_y , \
	interrupt_by_app , \
	begin_datetime , \
	end_datetime , \
	progress

#define	DBVLIST_dag_batches_info \
	:dag_batches_info_schedule_name , \
	:dag_batches_info_batch_name , \
	:dag_batches_info_batch_desc , \
	:dag_batches_info_view_pos_x , \
	:dag_batches_info_view_pos_y , \
	:dag_batches_info_interrupt_by_app , \
	:dag_batches_info_begin_datetime , \
	:dag_batches_info_end_datetime , \
	:dag_batches_info_progress

#define	DBVLLIST_dag_batches_info \
	:dag_batches_info_schedule_name :dag_batches_info_schedule_name_id , \
	:dag_batches_info_batch_name :dag_batches_info_batch_name_id , \
	:dag_batches_info_batch_desc :dag_batches_info_batch_desc_id , \
	:dag_batches_info_view_pos_x :dag_batches_info_view_pos_x_id , \
	:dag_batches_info_view_pos_y :dag_batches_info_view_pos_y_id , \
	:dag_batches_info_interrupt_by_app :dag_batches_info_interrupt_by_app_id , \
	:dag_batches_info_begin_datetime :dag_batches_info_begin_datetime_id , \
	:dag_batches_info_end_datetime :dag_batches_info_end_datetime_id , \
	:dag_batches_info_progress :dag_batches_info_progress_id

void DSCINITV_dag_batches_info();
void DSCVTOS_dag_batches_info( dag_batches_info *pst );
void DSCSTOV_dag_batches_info( dag_batches_info *pst );
void DSCTRIM_dag_batches_info( dag_batches_info *pst );

void DSCSQLACTION_OPEN_CURSOR_dag_batches_info_cursor1_SELECT_A_FROM_dag_batches_info_WHERE_schedule_name_E( dag_batches_info *pst );
void DSCSQLACTION_FETCH_CURSOR_dag_batches_info_cursor1( dag_batches_info *pst );
void DSCSQLACTION_CLOSE_CURSOR_dag_batches_info_cursor1();
void DSCSQLACTION_UPDATE_dag_batches_info_SET_begin_datetime_end_datetime_progress_WHERE_schedule_name_E_AND_batch_name_E( dag_batches_info *pst );

#endif
