/* It had generated by DirectStruct v1.4.5 */
#ifndef _H_dag_batches_tasks_ESQL_
#define _H_dag_batches_tasks_ESQL_

#define _PQSQL

#include <ecpglib.h>
#include <ecpgerrno.h>
#include <sqlca.h>

#include "IDL_dag_batches_tasks.dsc.h"

#undef SQLCODE
#define SQLCODE		(int)(sqlca.sqlcode)

#undef SQLSTATE
#define SQLSTATE	sqlca.sqlstate

#undef SQLDESC
#define SQLDESC		sqlca.sqlerrm.sqlerrmc

#ifndef SQLNOTFOUND
#define SQLNOTFOUND	100
#endif


EXEC SQL BEGIN DECLARE SECTION ;
	extern char dag_batches_tasks_schedule_name[ 64 + 1 ] ;	extern short dag_batches_tasks_schedule_name_id ;
	extern char dag_batches_tasks_batch_name[ 64 + 1 ] ;	extern short dag_batches_tasks_batch_name_id ;
	extern int dag_batches_tasks_order_index ;	extern short dag_batches_tasks_order_index_id ;
	extern char dag_batches_tasks_program_and_params[ 256 + 1 ] ;	extern short dag_batches_tasks_program_and_params_id ;
	extern int dag_batches_tasks_timeout ;	extern short dag_batches_tasks_timeout_id ;
	extern char dag_batches_tasks_begin_datetime[ 19 + 1 ] ;	extern short dag_batches_tasks_begin_datetime_id ;
	extern char dag_batches_tasks_end_datetime[ 19 + 1 ] ;	extern short dag_batches_tasks_end_datetime_id ;
	extern int dag_batches_tasks_progress ;	extern short dag_batches_tasks_progress_id ;
	extern int dag_batches_tasks_error ;	extern short dag_batches_tasks_error_id ;
	extern int dag_batches_tasks_status ;	extern short dag_batches_tasks_status_id ;
EXEC SQL END DECLARE SECTION ;

#define	TFLIST_dag_batches_tasks \
	schedule_name , \
	batch_name , \
	order_index , \
	program_and_params , \
	timeout , \
	begin_datetime , \
	end_datetime , \
	progress , \
	error , \
	status

#define	DBVLIST_dag_batches_tasks \
	:dag_batches_tasks_schedule_name , \
	:dag_batches_tasks_batch_name , \
	:dag_batches_tasks_order_index , \
	:dag_batches_tasks_program_and_params , \
	:dag_batches_tasks_timeout , \
	:dag_batches_tasks_begin_datetime , \
	:dag_batches_tasks_end_datetime , \
	:dag_batches_tasks_progress , \
	:dag_batches_tasks_error , \
	:dag_batches_tasks_status

#define	DBVLLIST_dag_batches_tasks \
	:dag_batches_tasks_schedule_name :dag_batches_tasks_schedule_name_id , \
	:dag_batches_tasks_batch_name :dag_batches_tasks_batch_name_id , \
	:dag_batches_tasks_order_index :dag_batches_tasks_order_index_id , \
	:dag_batches_tasks_program_and_params :dag_batches_tasks_program_and_params_id , \
	:dag_batches_tasks_timeout :dag_batches_tasks_timeout_id , \
	:dag_batches_tasks_begin_datetime :dag_batches_tasks_begin_datetime_id , \
	:dag_batches_tasks_end_datetime :dag_batches_tasks_end_datetime_id , \
	:dag_batches_tasks_progress :dag_batches_tasks_progress_id , \
	:dag_batches_tasks_error :dag_batches_tasks_error_id , \
	:dag_batches_tasks_status :dag_batches_tasks_status_id

void DSCINITV_dag_batches_tasks();
void DSCVTOS_dag_batches_tasks( dag_batches_tasks *pst );
void DSCSTOV_dag_batches_tasks( dag_batches_tasks *pst );
void DSCTRIM_dag_batches_tasks( dag_batches_tasks *pst );

void DSCSQLACTION_OPEN_CURSOR_dag_batches_tasks_cursor1_SELECT_A_FROM_dag_batches_tasks_WHERE_schedule_name_E( dag_batches_tasks *pst );
void DSCSQLACTION_FETCH_CURSOR_dag_batches_tasks_cursor1( dag_batches_tasks *pst );
void DSCSQLACTION_CLOSE_CURSOR_dag_batches_tasks_cursor1();
void DSCSQLACTION_OPEN_CURSOR_dag_batches_tasks_cursor2_SELECT_A_FROM_dag_batches_tasks_WHERE_schedule_name_E_AND_batch_name_E_ORDER_BY_order_index( dag_batches_tasks *pst );
void DSCSQLACTION_FETCH_CURSOR_dag_batches_tasks_cursor2( dag_batches_tasks *pst );
void DSCSQLACTION_CLOSE_CURSOR_dag_batches_tasks_cursor2();
void DSCSQLACTION_UPDATE_dag_batches_tasks_SET_begin_datetime_end_datetime_progress_error_status_WHERE_schedule_name_E_AND_batch_name_E_AND_order_index_E( dag_batches_tasks *pst );

#endif
