# 此文件由makelocal.sh自动生成
MAKEFILE_POSTFIX=.WINDOWS-MinGW
# 此文件由makeobj.sh自动生成
############################################################
# 项目名 : 
# 模块名 : 
# 备  注 : 
############################################################

###### 源文件配置区
# 编译宏
AR		=	ar
AFLAGS		=	rv
SOFLAGS		=	-shared -fPIC
ESOFLAGS	=	

# c源代码文件宏及推导规则
CC		=	gcc -g -fPIC -Wall -Werror -O2
CC_NOWARN	=	gcc -g -fPIC -O2

c_FILE_o	=	$(c_FILE:.c=.o)
c_FILE2_o	=	$(c_FILE2:.c=.o)
c_FILE3_o	=	$(c_FILE3:.c=.o)
c_FILE4_o	=	$(c_FILE4:.c=.o)
c_FILE5_o	=	$(c_FILE5:.c=.o)
c_FILE_CLEAN	=	$(c_FILE_o) $(c_FILE2_o) $(c_FILE3_o) $(c_FILE4_o) $(c_FILE5_o)

.SUFFIXES:.c
.c.o	:
	$(CC) $(CFLAGS) -c $<

c_FILE		=	\
			dc4c_test_master.c \
			dc4c_test_batch_master.c \
			dc4c_test_batch_master_stepbystep.c \
			dc4c_test_multi_batch_master.c \
			dc4c_test_multi_batch_master_stepbystep.c \
			dc4c_test_tfc_dag_master.c \
			dc4c_test_tfc_dag_master_stepbystep.c \
			dc4c_test_worker_hello.c \
			dc4c_test_worker_sleep.c \
			dc4c_test_worker_sleep_or_error.c \
			dc4c_test_worker_pi.c \
			$(c_FILE2) \

c_FILE2		=	\
			IDL_dag_schedule.dsc.c \
			IDL_dag_batches_direction.dsc.c \
			IDL_dag_batches_info.dsc.c \
			IDL_dag_batches_tasks.dsc.c \

###### 目标文件、安装目录配置区
include ../makeinstall
BIN		=	\
			dc4c_test_master \
			dc4c_test_batch_master \
			dc4c_test_batch_master_stepbystep \
			dc4c_test_multi_batch_master \
			dc4c_test_multi_batch_master_stepbystep \
			dc4c_test_tfc_dag_master \
			dc4c_test_tfc_dag_master_stepbystep \
			dc4c_test_worker_hello \
			dc4c_test_worker_sleep \
			dc4c_test_worker_sleep_or_error \
			dc4c_test_worker_pi \

BININST		=	$(_BININST)

###### 编译选项
CFLAGS		=	$(_CFLAGS) \
			-I$(_HDERINST_API) \
			-I$(_HDERINST_TFC_DAG) \
			-I$(_HDERBASE)/fasterjson \

###### 链接选项
LFLAGS		=	$(_LFLAGS) \
			-L$(_LIBINST) \
			-ldc4c_proto \
			-ldc4c_util \
			-ldc4c_api \
			-ldc4c_tfc_dag \
			-lfasterjson \

###### 额外宏定义区
CLEAN_ADDITION	=

###### 加载mktpl模板库
# 最终目标列表
all	:	$(OBJ) $(OBJ2) $(LIB) $(LIB2) $(SQL) $(NOCLEAN_OBJ) $(NOINST_OBJ) $(BIN) $(BIN2)

# 文件系统宏
CD		=	cd
RM		=	del
CP		=	mcopy
MV		=	move
MKDIR		=	mkdir

# 预定义源文件清理删除关联宏
_FILE_CLEAN	=	$(c_FILE_CLEAN) $(cpp_FILE_CLEAN) $(SQC_FILE_CLEAN) $(ec_FILE_CLEAN) $(ec_FILE2_CLEAN) $(csm_FILE_CLEAN) $(c_html_FILE_CLEAN) $(cui_FILE_CLEAN) $(dtd_FILE_CLEAN) $(prt_FILE_CLEAN) $(fmd_FILE_CLEAN) $(smd_FILE_CLEAN) $(def_FILE_CLEAN) $(act_FILE_CLEAN)

# 清理删除规则
clean		:
	$(RM) $(_FILE_CLEAN) $(BIN) $(BIN2) $(LIB) $(LIB2) $(OBJ) $(OBJ2) $(NOINST_OBJ) $(CLEAN_ADDITION)


# 预定义源代码缺省头文件宏
DFTHDER		=	$(csm_FILE_DFTHDER) $(cui_FILE_DFTHDER) $(dtd_FILE_DFTHDER) $(prt_FILE_DFTHDER) $(fmd_FILE_DFTHDER) $(smd_FILE_DFTHDER) $(def_FILE_DFTHDER) $(act_FILE_DFTHDER)

# 提交安装规则
install		:	all

ifneq ($(strip $(BIN)),)
ifneq ($(strip $(BININST)),)
	-$(MKDIR) "$(BININST)"
	$(CP) $(BIN) "$(BININST)/"
endif
endif
ifneq ($(strip $(BIN2)),)
ifneq ($(strip $(BININST2)),)
	-$(MKDIR) "$(BININST2)"
	$(CP) $(BIN2) "$(BININST2)/"
endif
endif


# 预定义源代码缺省头文件宏
DFTHDER		=	$(csm_FILE_DFTHDER) $(cui_FILE_DFTHDER) $(dtd_FILE_DFTHDER) $(prt_FILE_DFTHDER) $(fmd_FILE_DFTHDER) $(smd_FILE_DFTHDER) $(def_FILE_DFTHDER) $(act_FILE_DFTHDER)

# 提交安装规则
uninstall		:




###### 目标文件依赖关系
dc4c_test_master	:	dc4c_test_master.o
	$(CC) -o $@ dc4c_test_master.o $(LFLAGS)

dc4c_test_batch_master	:	dc4c_test_batch_master.o
	$(CC) -o $@ dc4c_test_batch_master.o $(LFLAGS)

dc4c_test_batch_master_stepbystep	:	dc4c_test_batch_master_stepbystep.o
	$(CC) -o $@ dc4c_test_batch_master_stepbystep.o $(LFLAGS)

dc4c_test_multi_batch_master	:	dc4c_test_multi_batch_master.o
	$(CC) -o $@ dc4c_test_multi_batch_master.o $(LFLAGS)

dc4c_test_multi_batch_master_stepbystep	:	dc4c_test_multi_batch_master_stepbystep.o
	$(CC) -o $@ dc4c_test_multi_batch_master_stepbystep.o $(LFLAGS)

dc4c_test_tfc_dag_master	:	dc4c_test_tfc_dag_master.o
	$(CC) -o $@ dc4c_test_tfc_dag_master.o $(LFLAGS) -ldc4c_tfc_dag

dc4c_test_tfc_dag_master_stepbystep	:	dc4c_test_tfc_dag_master_stepbystep.o
	$(CC) -o $@ dc4c_test_tfc_dag_master_stepbystep.o $(LFLAGS) -ldc4c_tfc_dag

dc4c_test_worker_hello	:	dc4c_test_worker_hello.o
	$(CC) -o $@ dc4c_test_worker_hello.o $(LFLAGS)

dc4c_test_worker_sleep	:	dc4c_test_worker_sleep.o
	$(CC) -o $@ dc4c_test_worker_sleep.o $(LFLAGS)

dc4c_test_worker_sleep_or_error	:	dc4c_test_worker_sleep_or_error.o
	$(CC) -o $@ dc4c_test_worker_sleep_or_error.o $(LFLAGS)

dc4c_test_worker_pi	:	dc4c_test_worker_pi.o
	$(CC) -o $@ dc4c_test_worker_pi.o $(LFLAGS) -lgmp

