# 此文件由makelocal.sh自动生成
MAKEFILE_POSTFIX=.Linux
# 此文件由makeobj.sh自动生成
############################################################
# 项目名 : 
# 模块名 : 
# 备  注 : 
############################################################

###### 源文件配置区
# 编译宏
AR		=	ar
AFLAGS		=	rv
SOFLAGS		=	-shared
ESOFLAGS	=	

# c源代码文件宏及推导规则
CC		=	gcc -g -fPIC -O2 -Wall -Werror -fno-strict-aliasing
CC_NOWARN	=	gcc -g -fPIC -O2

c_FILE_o	=	$(c_FILE:.c=.o)
c_FILE2_o	=	$(c_FILE2:.c=.o)
c_FILE3_o	=	$(c_FILE3:.c=.o)
c_FILE4_o	=	$(c_FILE4:.c=.o)
c_FILE5_o	=	$(c_FILE5:.c=.o)
c_FILE_CLEAN	=	$(c_FILE_o) $(c_FILE2_o) $(c_FILE3_o) $(c_FILE4_o) $(c_FILE5_o)

.SUFFIXES:.c
.c.o	:
	$(CC) $(CFLAGS) -c $<

c_FILE		=	\
			dc4c_test_master.c \
			dc4c_test_batch_master.c \
			dc4c_test_batch_master_stepbystep.c \
			dc4c_test_multi_batch_master.c \
			dc4c_test_multi_batch_master_stepbystep.c \
			dc4c_test_tfc_dag_master.c \
			dc4c_test_tfc_dag_master_stepbystep.c \
			dc4c_test_worker_hello.c \
			dc4c_test_worker_sleep.c \
			dc4c_test_worker_sleep_or_error.c \
			dc4c_test_worker_pi.c \
			$(c_FILE2) \

c_FILE2		=	\
			IDL_dag_schedule.dsc.c \
			IDL_dag_batches_direction.dsc.c \
			IDL_dag_batches_info.dsc.c \
			IDL_dag_batches_tasks.dsc.c \

ec_FILE		=	\
			dc4c_test_tfc_dag_master_pgsql_stepbystep.ec \
			$(ec_FILE2) \
			
ec_FILE2	=	\
			IDL_dag_schedule.dsc.ESQL.ec \
			IDL_dag_batches_direction.dsc.ESQL.ec \
			IDL_dag_batches_info.dsc.ESQL.ec \
			IDL_dag_batches_tasks.dsc.ESQL.ec \

###### 目标文件、安装目录配置区
BIN		=	\
			dc4c_test_master \
			dc4c_test_batch_master \
			dc4c_test_batch_master_stepbystep \
			dc4c_test_multi_batch_master \
			dc4c_test_multi_batch_master_stepbystep \
			dc4c_test_tfc_dag_master \
			dc4c_test_tfc_dag_master_stepbystep \
			dc4c_test_tfc_dag_master_pgsql_stepbystep \
			dc4c_test_worker_hello \
			dc4c_test_worker_sleep \
			dc4c_test_worker_sleep_or_error \
			dc4c_test_worker_pi \

BININST		=	/usr/local/bin

###### 编译选项
CFLAGS		=	-I. \
			-I/usr/local/include/fasterjson \
			-I/usr/local/include/dc4c_util \
			-I/usr/local/include/dc4c_proto \
			-I/usr/local/include/dc4c_api \
			-I/usr/local/include/dc4c_tfc_dag \

###### 链接选项
LFLAGS		=	-L. \
			-L/usr/local/lib \
			-lfasterjson \
			-ldc4c_util \
			-ldc4c_proto \
			-ldc4c_api \
			-ldc4c_tfc_dag \

###### 额外宏定义区
CLEAN_ADDITION	=

###### 加载mktpl模板库
# 最终目标列表
all	:	$(OBJ) $(OBJ2) $(LIB) $(LIB2) $(SQL) $(NOCLEAN_OBJ) $(NOINST_OBJ) $(BIN) $(BIN2)

# 文件系统宏
CD		=	cd
RM		=	rm -f
CP		=	cp -f
MV		=	mv -f
MKDIR		=	mkdir -p

# 预定义源文件清理删除关联宏
_FILE_CLEAN	=	$(c_FILE_CLEAN) $(cpp_FILE_CLEAN) $(SQC_FILE_CLEAN) $(ec_FILE_CLEAN) $(ec_FILE2_CLEAN) $(csm_FILE_CLEAN) $(c_html_FILE_CLEAN) $(cui_FILE_CLEAN) $(dtd_FILE_CLEAN) $(prt_FILE_CLEAN) $(fmd_FILE_CLEAN) $(smd_FILE_CLEAN) $(def_FILE_CLEAN) $(act_FILE_CLEAN) $(sml2c_FILE_CLEAN)

# 清理删除规则
.PHONY:clean
clean		:
	@for FILE in $(_FILE_CLEAN) $(BIN) $(BIN2) $(LIB) $(LIB2) $(OBJ) $(OBJ2) $(NOINST_OBJ) $(CLEAN_ADDITION) ; do \
		echo $(RM) $$FILE ; \
		$(RM) $$FILE ; \
	done


# 预定义源代码缺省头文件宏
DFTHDER		=	$(csm_FILE_DFTHDER) $(cui_FILE_DFTHDER) $(dtd_FILE_DFTHDER) $(prt_FILE_DFTHDER) $(fmd_FILE_DFTHDER) $(smd_FILE_DFTHDER) $(def_FILE_DFTHDER) $(act_FILE_DFTHDER) $(sml2c_FILE_DFTHDER)

# 提交安装规则
.PHONY:install
install		:	all

ifneq ($(strip $(BIN)),)
ifneq ($(strip $(BININST)),)
	@if [ ! -d "$(BININST)" ] ; then \
		echo $(MKDIR) $(BININST) ; \
		$(MKDIR) $(BININST) ; \
	fi ; \
	for FILE in `echo $(BIN)` ; do \
		echo $(CP) $$FILE $(BININST)/ ; \
		$(RM) $(BININST)/$$FILE ; \
		$(CP) $$FILE $(BININST)/ ; \
	done
endif
endif



###### 目标文件依赖关系
dc4c_test_master	:	dc4c_test_master.o
	$(CC) -o $@ dc4c_test_master.o $(LFLAGS)

dc4c_test_batch_master	:	dc4c_test_batch_master.o
	$(CC) -o $@ dc4c_test_batch_master.o $(LFLAGS)

dc4c_test_batch_master_stepbystep	:	dc4c_test_batch_master_stepbystep.o
	$(CC) -o $@ dc4c_test_batch_master_stepbystep.o $(LFLAGS)

dc4c_test_multi_batch_master	:	dc4c_test_multi_batch_master.o
	$(CC) -o $@ dc4c_test_multi_batch_master.o $(LFLAGS)

dc4c_test_multi_batch_master_stepbystep	:	dc4c_test_multi_batch_master_stepbystep.o
	$(CC) -o $@ dc4c_test_multi_batch_master_stepbystep.o $(LFLAGS)

dc4c_test_tfc_dag_master	:	dc4c_test_tfc_dag_master.o
	$(CC) -o $@ dc4c_test_tfc_dag_master.o $(LFLAGS) -ldc4c_tfc_dag

dc4c_test_tfc_dag_master_stepbystep	:	dc4c_test_tfc_dag_master_stepbystep.o
	$(CC) -o $@ dc4c_test_tfc_dag_master_stepbystep.o $(LFLAGS) -ldc4c_tfc_dag

dc4c_test_tfc_dag_master_pgsql_stepbystep	:	dc4c_test_tfc_dag_master_pgsql_stepbystep.o $(ec_FILE2_o)
	$(CC) -o $@ dc4c_test_tfc_dag_master_pgsql_stepbystep.o $(LFLAGS) $(ec_FILE2_o) -lecpg

dc4c_test_worker_hello	:	dc4c_test_worker_hello.o
	$(CC) -o $@ dc4c_test_worker_hello.o $(LFLAGS)

dc4c_test_worker_sleep	:	dc4c_test_worker_sleep.o
	$(CC) -o $@ dc4c_test_worker_sleep.o $(LFLAGS)

dc4c_test_worker_sleep_or_error	:	dc4c_test_worker_sleep_or_error.o
	$(CC) -o $@ dc4c_test_worker_sleep_or_error.o $(LFLAGS)

dc4c_test_worker_pi	:	dc4c_test_worker_pi.o
	$(CC) -o $@ dc4c_test_worker_pi.o $(LFLAGS) -lgmp

