/* It had generated by DirectStruct v1.4.5 */
#include "IDL_dag_schedule.dsc.h"

int DSCINIT_dag_schedule( dag_schedule *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(dag_schedule) );
	return 0;
}
