/* It had generated by DirectStruct v1.4.5 */
#ifndef _H_dag_batches_direction_ESQL_
#define _H_dag_batches_direction_ESQL_

#define _PQSQL

#include <ecpglib.h>
#include <ecpgerrno.h>
#include <sqlca.h>

#include "IDL_dag_batches_direction.dsc.h"

#undef SQLCODE
#define SQLCODE		(int)(sqlca.sqlcode)

#undef SQLSTATE
#define SQLSTATE	sqlca.sqlstate

#undef SQLDESC
#define SQLDESC		sqlca.sqlerrm.sqlerrmc

#ifndef SQLNOTFOUND
#define SQLNOTFOUND	100
#endif


EXEC SQL BEGIN DECLARE SECTION ;
	extern char dag_batches_direction_schedule_name[ 64 + 1 ] ;	extern short dag_batches_direction_schedule_name_id ;
	extern char dag_batches_direction_from_batch[ 64 + 1 ] ;	extern short dag_batches_direction_from_batch_id ;
	extern char dag_batches_direction_to_batch[ 64 + 1 ] ;	extern short dag_batches_direction_to_batch_id ;
EXEC SQL END DECLARE SECTION ;

#define	TFLIST_dag_batches_direction \
	schedule_name , \
	from_batch , \
	to_batch

#define	DBVLIST_dag_batches_direction \
	:dag_batches_direction_schedule_name , \
	:dag_batches_direction_from_batch , \
	:dag_batches_direction_to_batch

#define	DBVLLIST_dag_batches_direction \
	:dag_batches_direction_schedule_name :dag_batches_direction_schedule_name_id , \
	:dag_batches_direction_from_batch :dag_batches_direction_from_batch_id , \
	:dag_batches_direction_to_batch :dag_batches_direction_to_batch_id

void DSCINITV_dag_batches_direction();
void DSCVTOS_dag_batches_direction( dag_batches_direction *pst );
void DSCSTOV_dag_batches_direction( dag_batches_direction *pst );
void DSCTRIM_dag_batches_direction( dag_batches_direction *pst );

void DSCSQLACTION_OPEN_CURSOR_dag_batches_direction_cursor1_SELECT_A_FROM_dag_batches_direction_WHERE_schedule_name_E( dag_batches_direction *pst );
void DSCSQLACTION_FETCH_CURSOR_dag_batches_direction_cursor1( dag_batches_direction *pst );
void DSCSQLACTION_CLOSE_CURSOR_dag_batches_direction_cursor1();

#endif
