/* It had generated by DirectStruct v1.4.5 */
#include "IDL_dag_batches_tasks.dsc.h"

#ifndef FUNCNAME_DSCLOG_dag_batches_tasks
#define FUNCNAME_DSCLOG_dag_batches_tasks	DSCLOG_dag_batches_tasks
#endif

#ifndef PREFIX_DSCLOG_dag_batches_tasks
#define PREFIX_DSCLOG_dag_batches_tasks	printf( 
#endif

#ifndef NEWLINE_DSCLOG_dag_batches_tasks
#define NEWLINE_DSCLOG_dag_batches_tasks	"\n"
#endif

int FUNCNAME_DSCLOG_dag_batches_tasks( dag_batches_tasks *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.schedule_name[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->schedule_name );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.batch_name[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->batch_name );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.program_and_params[%s]" NEWLINE_DSCLOG_dag_batches_tasks , pst->program_and_params );
	PREFIX_DSCLOG_dag_batches_tasks "dag_batches_tasks.timeout[%d]" NEWLINE_DSCLOG_dag_batches_tasks , pst->timeout );
	return 0;
}
