/* It had generated by DirectStruct v1.4.5 */
#include "IDL_dag_batches_tasks.dsc.h"

int DSCINIT_dag_batches_tasks( dag_batches_tasks *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(dag_batches_tasks) );
	return 0;
}
