/* It had generated by DirectStruct v1.4.4 */
#include "IDL_dag_schedule_config.dsc.h"

#ifndef FUNCNAME_DSCLOG_dag_schedule_config
#define FUNCNAME_DSCLOG_dag_schedule_config	DSCLOG_dag_schedule_config
#endif

#ifndef PREFIX_DSCLOG_dag_schedule_config
#define PREFIX_DSCLOG_dag_schedule_config	printf( 
#endif

#ifndef NEWLINE_DSCLOG_dag_schedule_config
#define NEWLINE_DSCLOG_dag_schedule_config	"\n"
#endif

int FUNCNAME_DSCLOG_dag_schedule_config( dag_schedule_config *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
		PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.schedule.schedule_name[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->schedule.schedule_name );
		PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.schedule.schedule_desc[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->schedule.schedule_desc );
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches._batches_direction_count[%d]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches._batches_direction_count );
			for( index[2] = 0 ; index[2] < pst->batches._batches_direction_count ; index[2]++ )
			{
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_direction[index[2]].from[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_direction[index[2]].from );
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_direction[index[2]].to[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_direction[index[2]].to );
			}
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches._batches_info_count[%d]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches._batches_info_count );
			for( index[2] = 0 ; index[2] < pst->batches._batches_info_count ; index[2]++ )
			{
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]].name[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]].name );
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]].desc[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]].desc );
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]].view_pos_x[%d]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]].view_pos_x );
			PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]].view_pos_y[%d]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]].view_pos_y );
				PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]]._tasks_count[%d]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]]._tasks_count );
				for( index[3] = 0 ; index[3] < pst->batches.batches_info[index[2]]._tasks_count ; index[3]++ )
				{
				PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]].tasks[index[3]].program_and_params[%s]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]].tasks[index[3]].program_and_params );
				PREFIX_DSCLOG_dag_schedule_config "dag_schedule_config.batches.batches_info[index[2]].tasks[index[3]].timeout[%d]" NEWLINE_DSCLOG_dag_schedule_config , pst->batches.batches_info[index[2]].tasks[index[3]].timeout );
				}
			}
	return 0;
}
