/* It had generated by DirectStruct v1.4.4 */
#include "IDL_dag_batches_info.dsc.h"

int DSCINIT_dag_batches_info( dag_batches_info *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(dag_batches_info) );
	return 0;
}
