-- It had generated by DirectStruct v1.4.4

CREATE TABLE dag_schedule
(
	order_index	INTEGER NOT NULL ,
	schedule_name	CHARACTER VARYING(64) NOT NULL ,
	schedule_desc	CHARACTER VARYING(256)
) ;

CREATE UNIQUE INDEX dag_schedule_idx1 ON dag_schedule ( order_index ) ;

CREATE UNIQUE INDEX dag_schedule_idx2 ON dag_schedule ( schedule_name ) ;
