-- It had generated by DirectStruct v1.4.4

CREATE TABLE dag_batches_tasks
(
	schedule_name	CHARACTER VARYING(64) NOT NULL ,
	batch_name	CHARACTER VARYING(64) NOT NULL ,
	order_index	INTEGER NOT NULL ,
	program_and_params	CHARACTER VARYING(256) NOT NULL ,
	timeout	INTEGER NOT NULL
) ;

CREATE UNIQUE INDEX dag_batches_tasks_idx1 ON dag_batches_tasks ( schedule_name , batch_name , order_index ) ;
