-- It had generated by DirectStruct v1.4.5

CREATE TABLE dag_schedule
(
	order_index	INTEGER ,
	schedule_name	CHARACTER VARYING(64) ,
	schedule_desc	CHARACTER VARYING(256)
) ;

CREATE UNIQUE INDEX dag_schedule_idx1 ON dag_schedule ( schedule_name ) ;
