-- It had generated by DirectStruct v1.4.4

CREATE TABLE dag_batches_info
(
	schedule_name	CHARACTER VARYING(64) ,
	batch_name	CHARACTER VARYING(64) ,
	batch_desc	CHARACTER VARYING(64) ,
	view_pos_x	INTEGER ,
	view_pos_y	INTEGER
) ;

CREATE UNIQUE INDEX dag_batches_info_idx1 ON dag_batches_info ( schedule_name , batch_name ) ;
