/* It had generated by DirectStruct v1.4.5 */
#include "IDL_dag_schedule_configfile.dsc.h"

#ifndef FUNCNAME_DSCLOG_dag_schedule_configfile
#define FUNCNAME_DSCLOG_dag_schedule_configfile	DSCLOG_dag_schedule_configfile
#endif

#ifndef PREFIX_DSCLOG_dag_schedule_configfile
#define PREFIX_DSCLOG_dag_schedule_configfile	printf( 
#endif

#ifndef NEWLINE_DSCLOG_dag_schedule_configfile
#define NEWLINE_DSCLOG_dag_schedule_configfile	"\n"
#endif

int FUNCNAME_DSCLOG_dag_schedule_configfile( dag_schedule_configfile *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
		PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.schedule.schedule_name[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->schedule.schedule_name );
		PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.schedule.schedule_desc[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->schedule.schedule_desc );
		PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.schedule.begin_datetime[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->schedule.begin_datetime );
		PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.schedule.end_datetime[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->schedule.end_datetime );
		PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.schedule.progress[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->schedule.progress );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches._batches_info_count[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches._batches_info_count );
			for( index[2] = 0 ; index[2] < pst->batches._batches_info_count ; index[2]++ )
			{
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].batch_name[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].batch_name );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].batch_desc[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].batch_desc );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].view_pos_x[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].view_pos_x );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].view_pos_y[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].view_pos_y );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].interrupt_by_app[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].interrupt_by_app );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].begin_datetime[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].begin_datetime );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].end_datetime[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].end_datetime );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].progress[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].progress );
				PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]]._tasks_count[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]]._tasks_count );
				for( index[3] = 0 ; index[3] < pst->batches.batches_info[index[2]]._tasks_count ; index[3]++ )
				{
				PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].tasks[index[3]].order_index[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].tasks[index[3]].order_index );
				PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].tasks[index[3]].program_and_params[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].tasks[index[3]].program_and_params );
				PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].tasks[index[3]].timeout[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].tasks[index[3]].timeout );
				PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_info[index[2]].tasks[index[3]].progress[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_info[index[2]].tasks[index[3]].progress );
				}
			}
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches._batches_direction_count[%d]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches._batches_direction_count );
			for( index[2] = 0 ; index[2] < pst->batches._batches_direction_count ; index[2]++ )
			{
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_direction[index[2]].from_batch[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_direction[index[2]].from_batch );
			PREFIX_DSCLOG_dag_schedule_configfile "dag_schedule_configfile.batches.batches_direction[index[2]].to_batch[%s]" NEWLINE_DSCLOG_dag_schedule_configfile , pst->batches.batches_direction[index[2]].to_batch );
			}
	return 0;
}
