/* It had generated by DirectStruct v1.4.4 */
#include "IDL_dag_batches_direction.dsc.h"

int DSCINIT_dag_batches_direction( dag_batches_direction *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(dag_batches_direction) );
	return 0;
}
