/* It had generated by DirectStruct v1.4.4 */
#include "IDL_dag_schedule_config.dsc.h"

int DSCINIT_dag_schedule_config( dag_schedule_config *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(dag_schedule_config) );
			for( index[2] = 0 ; index[2] < 100 ; index[2]++ )
			{
			pst->batches._batches_direction_size = 100 ;
			}
			for( index[2] = 0 ; index[2] < 100 ; index[2]++ )
			{
				for( index[3] = 0 ; index[3] < 100 ; index[3]++ )
				{
				pst->batches.batches_info[index[3]]._tasks_size = 100 ;
				}
			pst->batches._batches_info_size = 100 ;
			}
	return 0;
}

#include "fasterjson.h"

int DSCSERIALIZE_JSON_dag_schedule_config( dag_schedule_config *pst , char *encoding , char *buf , int *p_len )
{
	int	remain_len ;
	int	len ;
	char	tabs[10+1] ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	remain_len = (*p_len) ;
	memset( tabs , '\t' , 10 );
	len=SNPRINTF(buf,remain_len,"{\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	\"schedule\" : \n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	{\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"schedule_name\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->schedule.schedule_name,strlen(pst->schedule.schedule_name),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"schedule_desc\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->schedule.schedule_desc,strlen(pst->schedule.schedule_desc),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	} ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	\"batches\" : \n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	{\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		\"batches_direction\" : \n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		[\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
				for( index[2] = 0 ; index[2]<pst->batches._batches_direction_count ; index[2]++ )
				{
	len=SNPRINTF(buf,remain_len,"		{\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"from\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->batches.batches_direction[index[2]].from,strlen(pst->batches.batches_direction[index[2]].from),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"to\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->batches.batches_direction[index[2]].to,strlen(pst->batches.batches_direction[index[2]].to),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
				if((pst->batches._batches_direction_count==0)?(index[2]<100-1):(index[2]<pst->batches._batches_direction_count-1))
				{ len=SNPRINTF(buf,remain_len,"		} ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len; }
				else
				{ len=SNPRINTF(buf,remain_len,"		}\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len; }
				}
	len=SNPRINTF(buf,remain_len,"		] ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		\"batches_info\" : \n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"		[\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
				for( index[2] = 0 ; index[2]<pst->batches._batches_info_count ; index[2]++ )
				{
	len=SNPRINTF(buf,remain_len,"		{\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"name\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->batches.batches_info[index[2]].name,strlen(pst->batches.batches_info[index[2]].name),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"desc\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->batches.batches_info[index[2]].desc,strlen(pst->batches.batches_info[index[2]].desc),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"view_pos_x\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%d",pst->batches.batches_info[index[2]].view_pos_x); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"view_pos_y\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%d",pst->batches.batches_info[index[2]].view_pos_y); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			\"tasks\" : \n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"			[\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
					for( index[3] = 0 ; index[3]<pst->batches.batches_info[index[2]]._tasks_count ; index[3]++ )
					{
	len=SNPRINTF(buf,remain_len,"			{\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"				"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"program_and_params\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->batches.batches_info[index[2]].tasks[index[3]].program_and_params,strlen(pst->batches.batches_info[index[2]].tasks[index[3]].program_and_params),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len," ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"				"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"timeout\" : "); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%d",pst->batches.batches_info[index[2]].tasks[index[3]].timeout); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
					if((pst->batches.batches_info[index[2]]._tasks_count==0)?(index[3]<100-1):(index[3]<pst->batches.batches_info[index[2]]._tasks_count-1))
					{ len=SNPRINTF(buf,remain_len,"			} ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len; }
					else
					{ len=SNPRINTF(buf,remain_len,"			}\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len; }
					}
	len=SNPRINTF(buf,remain_len,"			]\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
				if((pst->batches._batches_info_count==0)?(index[2]<100-1):(index[2]<pst->batches._batches_info_count-1))
				{ len=SNPRINTF(buf,remain_len,"		} ,\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len; }
				else
				{ len=SNPRINTF(buf,remain_len,"		}\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len; }
				}
	len=SNPRINTF(buf,remain_len,"		]\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"	}\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"}\n"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	
	if( p_len ) (*p_len) = (*p_len) - remain_len ;
	
	return 0;
}

funcCallbackOnJsonNode CallbackOnJsonNode_dag_schedule_config ;
int CallbackOnJsonNode_dag_schedule_config( int type , char *jpath , int jpath_len , int jpath_size , char *node , int node_len , char *content , int content_len , void *p )
{
	dag_schedule_config	*pst = (dag_schedule_config*)p ;
	int	index[10] = { 0 } ;
	int	len ;
	
	index[0] = 0 ;
	len = 0 ;
	
	if( type & FASTERJSON_NODE_BRANCH )
	{
		if( type & FASTERJSON_NODE_ENTER )
		{
			if( jpath_len == 26 && strncmp( jpath , "/batches/batches_direction" , jpath_len ) == 0 )
			{if(pst->batches._batches_direction_count>=100)return -8;}
			if( jpath_len == 21 && strncmp( jpath , "/batches/batches_info" , jpath_len ) == 0 )
			{if(pst->batches._batches_info_count>=100)return -8;}
				if( jpath_len == 27 && strncmp( jpath , "/batches/batches_info/tasks" , jpath_len ) == 0 )
				{if(pst->batches.batches_info[pst->batches._batches_info_count]._tasks_count>=100)return -8;}
		}
		else if( type & FASTERJSON_NODE_LEAVE )
		{
			if( jpath_len == 26 && strncmp( jpath , "/batches/batches_direction" , jpath_len ) == 0 )
			{pst->batches._batches_direction_count++;}
			if( jpath_len == 21 && strncmp( jpath , "/batches/batches_info" , jpath_len ) == 0 )
			{pst->batches._batches_info_count++;}
				if( jpath_len == 27 && strncmp( jpath , "/batches/batches_info/tasks" , jpath_len ) == 0 )
				{pst->batches.batches_info[pst->batches._batches_info_count]._tasks_count++;}
		}
	}
	else if( type & FASTERJSON_NODE_LEAF )
	{
			/* schedule_name */
			if( jpath_len == 23 && strncmp( jpath , "/schedule/schedule_name" , jpath_len ) == 0 )
			{JSONUNESCAPE_FOLD(content,content_len,pst->schedule.schedule_name,len,sizeof(pst->schedule.schedule_name)-1); if(len<0)return -7;}
			/* schedule_desc */
			if( jpath_len == 23 && strncmp( jpath , "/schedule/schedule_desc" , jpath_len ) == 0 )
			{JSONUNESCAPE_FOLD(content,content_len,pst->schedule.schedule_desc,len,sizeof(pst->schedule.schedule_desc)-1); if(len<0)return -7;}
				/* from */
				if( jpath_len == 31 && strncmp( jpath , "/batches/batches_direction/from" , jpath_len ) == 0 )
				{JSONUNESCAPE_FOLD(content,content_len,pst->batches.batches_direction[pst->batches._batches_direction_count].from,len,sizeof(pst->batches.batches_direction[pst->batches._batches_direction_count].from)-1); if(len<0)return -7;}
				/* to */
				if( jpath_len == 29 && strncmp( jpath , "/batches/batches_direction/to" , jpath_len ) == 0 )
				{JSONUNESCAPE_FOLD(content,content_len,pst->batches.batches_direction[pst->batches._batches_direction_count].to,len,sizeof(pst->batches.batches_direction[pst->batches._batches_direction_count].to)-1); if(len<0)return -7;}
				/* name */
				if( jpath_len == 26 && strncmp( jpath , "/batches/batches_info/name" , jpath_len ) == 0 )
				{JSONUNESCAPE_FOLD(content,content_len,pst->batches.batches_info[pst->batches._batches_info_count].name,len,sizeof(pst->batches.batches_info[pst->batches._batches_info_count].name)-1); if(len<0)return -7;}
				/* desc */
				if( jpath_len == 26 && strncmp( jpath , "/batches/batches_info/desc" , jpath_len ) == 0 )
				{JSONUNESCAPE_FOLD(content,content_len,pst->batches.batches_info[pst->batches._batches_info_count].desc,len,sizeof(pst->batches.batches_info[pst->batches._batches_info_count].desc)-1); if(len<0)return -7;}
				/* view_pos_x */
				if( jpath_len == 32 && strncmp( jpath , "/batches/batches_info/view_pos_x" , jpath_len ) == 0 )
				{NATOI(content,content_len,pst->batches.batches_info[pst->batches._batches_info_count].view_pos_x);}
				/* view_pos_y */
				if( jpath_len == 32 && strncmp( jpath , "/batches/batches_info/view_pos_y" , jpath_len ) == 0 )
				{NATOI(content,content_len,pst->batches.batches_info[pst->batches._batches_info_count].view_pos_y);}
					/* program_and_params */
					if( jpath_len == 46 && strncmp( jpath , "/batches/batches_info/tasks/program_and_params" , jpath_len ) == 0 )
					{JSONUNESCAPE_FOLD(content,content_len,pst->batches.batches_info[pst->batches._batches_info_count].tasks[pst->batches.batches_info[pst->batches._batches_info_count]._tasks_count].program_and_params,len,sizeof(pst->batches.batches_info[pst->batches._batches_info_count].tasks[pst->batches.batches_info[pst->batches._batches_info_count]._tasks_count].program_and_params)-1); if(len<0)return -7;}
					/* timeout */
					if( jpath_len == 35 && strncmp( jpath , "/batches/batches_info/tasks/timeout" , jpath_len ) == 0 )
					{NATOI(content,content_len,pst->batches.batches_info[pst->batches._batches_info_count].tasks[pst->batches.batches_info[pst->batches._batches_info_count]._tasks_count].timeout);}
	}
	
	return 0;
}

int DSCDESERIALIZE_JSON_dag_schedule_config( char *encoding , char *buf , int *p_len , dag_schedule_config *pst )
{
	char	jpath[ 1024 + 1 ] ;
	int	nret = 0 ;
	memset( jpath , 0x00 , sizeof(jpath) );
	nret = TravelJsonBuffer( buf , jpath , sizeof(jpath) , & CallbackOnJsonNode_dag_schedule_config , (void*)pst ) ;
	if( nret )
		return nret;
	
	return 0;
}
