/* It had generated by DirectStruct v1.4.4 */
#include "IDL_dag_batches_direction.dsc.h"

#ifndef FUNCNAME_DSCLOG_dag_batches_direction
#define FUNCNAME_DSCLOG_dag_batches_direction	DSCLOG_dag_batches_direction
#endif

#ifndef PREFIX_DSCLOG_dag_batches_direction
#define PREFIX_DSCLOG_dag_batches_direction	printf( 
#endif

#ifndef NEWLINE_DSCLOG_dag_batches_direction
#define NEWLINE_DSCLOG_dag_batches_direction	"\n"
#endif

int FUNCNAME_DSCLOG_dag_batches_direction( dag_batches_direction *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_dag_batches_direction "dag_batches_direction.schedule_name[%s]" NEWLINE_DSCLOG_dag_batches_direction , pst->schedule_name );
	PREFIX_DSCLOG_dag_batches_direction "dag_batches_direction.from_batch[%s]" NEWLINE_DSCLOG_dag_batches_direction , pst->from_batch );
	PREFIX_DSCLOG_dag_batches_direction "dag_batches_direction.to_batch[%s]" NEWLINE_DSCLOG_dag_batches_direction , pst->to_batch );
	return 0;
}
