/* It had generated by DirectStruct v1.3.2 */
#include "IDL_execute_program_request.dsc.h"

int DSCINIT_execute_program_request( execute_program_request *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(execute_program_request) );
	return 0;
}

#include "fasterjson.h"

int DSCSERIALIZE_JSON_COMPACT_execute_program_request( execute_program_request *pst , char *encoding , char *buf , int *p_len )
{
	int	remain_len ;
	int	len ;
	char	tabs[10+1] ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	remain_len = (*p_len) - 1 ;
	memset( tabs , '\t' , 10 );
	len=SNPRINTF(buf,remain_len,"{"); if( len <= 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"program\":"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%s",pst->program); JSONESCAPE_EXPAND(buf,len,remain_len); if( len < 0 ) return -1;
	len=SNPRINTF(buf,remain_len,"\""); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"md5_exp\":"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%s",pst->md5_exp); JSONESCAPE_EXPAND(buf,len,remain_len); if( len < 0 ) return -1;
	len=SNPRINTF(buf,remain_len,"\""); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"params\":"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%s",pst->params); JSONESCAPE_EXPAND(buf,len,remain_len); if( len < 0 ) return -1;
	len=SNPRINTF(buf,remain_len,"\""); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"}"); if( len <= 0 ) return -1; buf+=len; remain_len-=len;
	
	if( p_len ) (*p_len) = (*p_len)-1 - remain_len ;
	
	return 0;
}

funcCallbackOnJsonNode CallbackOnJsonNode_execute_program_request ;
int CallbackOnJsonNode_execute_program_request( int type , char *jpath , int jpath_len , int jpath_size , char *node , int node_len , char *content , int content_len , void *p )
{
	execute_program_request	*pst = (execute_program_request*)p ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	
	if( type & FASTERJSON_NODE_BRANCH )
	{
		if( type & FASTERJSON_NODE_ENTER )
		{
		}
		else if( type & FASTERJSON_NODE_LEAVE )
		{
		}
	}
	else if( type & FASTERJSON_NODE_LEAF )
	{
		/* program */
		if( jpath_len == 8 && strncmp( jpath , "/program" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->program,sizeof(pst->program)-1,return -7);}
		/* md5_exp */
		if( jpath_len == 8 && strncmp( jpath , "/md5_exp" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->md5_exp,sizeof(pst->md5_exp)-1,return -7);}
		/* params */
		if( jpath_len == 7 && strncmp( jpath , "/params" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->params,sizeof(pst->params)-1,return -7);}
	}
	
	return 0;
}

int DSCDESERIALIZE_JSON_COMPACT_execute_program_request( char *encoding , char *buf , int *p_len , execute_program_request *pst )
{
	char	jpath[ 1024 + 1 ] ;
	int	nret = 0 ;
	memset( jpath , 0x00 , sizeof(jpath) );
	nret = TravelJsonBuffer( buf , jpath , sizeof(jpath) , & CallbackOnJsonNode_execute_program_request , (void*)pst ) ;
	if( nret )
		return nret;
	
	return 0;
}
