/* It had generated by DirectStruct v1.3.2 */
#include "IDL_worker_notice_response.dsc.h"

#ifndef FUNCNAME_DSCLOG_worker_notice_response
#define FUNCNAME_DSCLOG_worker_notice_response	DSCLOG_worker_notice_response
#endif

#ifndef PREFIX_DSCLOG_worker_notice_response
#define PREFIX_DSCLOG_worker_notice_response	printf( 
#endif

#ifndef NEWLINE_DSCLOG_worker_notice_response
#define NEWLINE_DSCLOG_worker_notice_response	"\n"
#endif

int FUNCNAME_DSCLOG_worker_notice_response( worker_notice_response *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_worker_notice_response "worker_notice_response.response_code[%d]" NEWLINE_DSCLOG_worker_notice_response , pst->response_code );
	return 0;
}
