/* It had generated by DirectStruct v1.4.5 */
#include "IDL_execute_program_request.dsc.h"

int DSCINIT_execute_program_request( execute_program_request *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(execute_program_request) );
	return 0;
}

#include "fasterjson.h"

int DSCSERIALIZE_JSON_COMPACT_execute_program_request( execute_program_request *pst , char *encoding , char *buf , int *p_len )
{
	int	remain_len ;
	int	len ;
	char	tabs[10+1] ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	remain_len = (*p_len) ;
	memset( tabs , '\t' , 10 );
	len=SNPRINTF(buf,remain_len,"{"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"ip\":"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->ip,strlen(pst->ip),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"port\":"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%d",pst->port); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"tid\":"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->tid,strlen(pst->tid),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"program_and_params\":"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->program_and_params,strlen(pst->program_and_params),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"program_md5_exp\":"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	JSONESCAPE_EXPAND(pst->program_md5_exp,strlen(pst->program_md5_exp),buf,len,remain_len); if(len<0)return -7; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\""); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,","); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"\"timeout\":"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"%d",pst->timeout); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"}"); if(len<0||remain_len<len)return -1; buf+=len; remain_len-=len;
	
	if( p_len ) (*p_len) = (*p_len) - remain_len ;
	
	return 0;
}

funcCallbackOnJsonNode CallbackOnJsonNode_execute_program_request ;
int CallbackOnJsonNode_execute_program_request( int type , char *jpath , int jpath_len , int jpath_size , char *node , int node_len , char *content , int content_len , void *p )
{
	execute_program_request	*pst = (execute_program_request*)p ;
	int	index[10] = { 0 } ;
	int	len ;
	
	index[0] = 0 ;
	len = 0 ;
	
	if( type & FASTERJSON_NODE_BRANCH )
	{
		if( type & FASTERJSON_NODE_ENTER )
		{
		}
		else if( type & FASTERJSON_NODE_LEAVE )
		{
		}
	}
	else if( type & FASTERJSON_NODE_LEAF )
	{
		/* ip */
		if( jpath_len == 3 && strncmp( jpath , "/ip" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->ip,len,sizeof(pst->ip)-1); if(len<0)return -7;}
		/* port */
		if( jpath_len == 5 && strncmp( jpath , "/port" , jpath_len ) == 0 )
		{NATOI(content,content_len,pst->port);}
		/* tid */
		if( jpath_len == 4 && strncmp( jpath , "/tid" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->tid,len,sizeof(pst->tid)-1); if(len<0)return -7;}
		/* program_and_params */
		if( jpath_len == 19 && strncmp( jpath , "/program_and_params" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->program_and_params,len,sizeof(pst->program_and_params)-1); if(len<0)return -7;}
		/* program_md5_exp */
		if( jpath_len == 16 && strncmp( jpath , "/program_md5_exp" , jpath_len ) == 0 )
		{JSONUNESCAPE_FOLD(content,content_len,pst->program_md5_exp,len,sizeof(pst->program_md5_exp)-1); if(len<0)return -7;}
		/* timeout */
		if( jpath_len == 8 && strncmp( jpath , "/timeout" , jpath_len ) == 0 )
		{NATOI(content,content_len,pst->timeout);}
	}
	
	return 0;
}

int DSCDESERIALIZE_JSON_COMPACT_execute_program_request( char *encoding , char *buf , int *p_len , execute_program_request *pst )
{
	char	jpath[ 1024 + 1 ] ;
	int	nret = 0 ;
	memset( jpath , 0x00 , sizeof(jpath) );
	nret = TravelJsonBuffer( buf , jpath , sizeof(jpath) , & CallbackOnJsonNode_execute_program_request , (void*)pst ) ;
	if( nret )
		return nret;
	
	return 0;
}
